# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systeminfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_systemInfoDialog(object):
    def setupUi(self, systemInfoDialog):
        systemInfoDialog.setObjectName("systemInfoDialog")
        systemInfoDialog.resize(400, 300)
        self.cpuLabel = QtWidgets.QLabel(systemInfoDialog)
        self.cpuLabel.setGeometry(QtCore.QRect(30, 30, 151, 18))
        self.cpuLabel.setObjectName("cpuLabel")
        self.ramLabel = QtWidgets.QLabel(systemInfoDialog)
        self.ramLabel.setGeometry(QtCore.QRect(30, 60, 151, 18))
        self.ramLabel.setObjectName("ramLabel")
        self.gpuLabel = QtWidgets.QLabel(systemInfoDialog)
        self.gpuLabel.setGeometry(QtCore.QRect(30, 90, 151, 18))
        self.gpuLabel.setObjectName("gpuLabel")
        self.quitButton = QtWidgets.QPushButton(systemInfoDialog)
        self.quitButton.setGeometry(QtCore.QRect(310, 260, 88, 34))
        self.quitButton.setObjectName("quitButton")

        self.retranslateUi(systemInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(systemInfoDialog)

    def retranslateUi(self, systemInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        systemInfoDialog.setWindowTitle(_translate("systemInfoDialog", "System Info"))
        self.cpuLabel.setText(_translate("systemInfoDialog", "CPU:"))
        self.ramLabel.setText(_translate("systemInfoDialog", "RAM:"))
        self.gpuLabel.setText(_translate("systemInfoDialog", "GPU:"))
        self.quitButton.setText(_translate("systemInfoDialog", "Quit"))
